# ZooKeeper
zookeeper:
    image: mesosphere/mesos:0.22.1-1.0.ubuntu1404
    command: /usr/share/zookeeper/bin/zkServer.sh start-foreground
# Mesos master
mesosmaster:
    image: mesosphere/mesos-master:0.22.1-1.0.ubuntu1404
    ports:
        - "5050:5050"
    links:
        - "zookeeper:zk"
    environment:
        - MESOS_ZK=zk://zk:2181/mesos
        - MESOS_LOG_DIR=/var/log/mesos
        - MESOS_WORK_DIR=/var/lib/mesos
        - MESOS_QUORUM=1
# Mesos slave
mesosslave:
    image: mesosphere/mesos-slave:0.22.1-1.0.ubuntu1404
    command: --containerizers=docker
    links:
        - "zookeeper:zk"
        - "mesosmaster:master"
    environment:
        - MESOS_MASTER=zk://zk:2181/mesos
        - MESOS_LOG_DIR=/var/log/mesos
        - MESOS_LOGGING_LEVEL=INFO
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker:ro
        - /sys:/sys
# NATS distributed queue
gnatsd:
    image: apcera/gnatsd
# TAURUS framewowrk
taurus:
    build: ./cmd/framework/
    ports:
        - "8080:8080"
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /usr/bin/docker:/usr/bin/docker:ro
    links:
        - "mesosmaster:master"
        - "mesosslave:slave"
        - "gnatsd:queue"
    environment:
        - MESOS_MASTER=master:5050
        - TASK_QUEUE=nats://queue:4222
    volumes:
        - /var/lib:/tmp
